
services:
  n8n:
    image: n8nio/n8n:latest
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=ton_mot_de_passe_securise
      - GENERIC_TIMEZONE=Europe/Paris
      - NODE_FUNCTION_ALLOW_BUILTIN=sqlite3
      - NODE_FUNCTION_ALLOW_EXTERNAL=sqlite3
    volumes:
      - n8n_data:/home/node/.n8n
      - "c:/Users/alexd/OneDrive/Bureau/Projet/strong v3/string_v3:/home/node/mobile_project"

volumes:
  n8n_data: